name: Update API Specs

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
        types: [opened]

jobs:
    update-specs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout docs repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install -g swagger-combine

            - name: Clone Corbado repository
              run: |
                  git clone https://github.com/corbado/corbado.git /tmp/corbado
                  cp /tmp/corbado/backend/openapi/backend_api_public_v2.yml openapi/backend-public-v2.yml
                  cp /tmp/corbado/backend/openapi/common.yml openapi/common-specs.yml

            - name: Merge API specs
              run: swagger-combine openapi/merge-config.json -o content/spec.yml

            - name: Configure Git
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'

            - name: Commit and push changes
              run: |
                  git add content/spec.yml
                  git commit -m "chore: update API specs" || exit 0
                  git push
